// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"chat/app/user/service/internal/biz"
	"chat/app/user/service/internal/conf"
	"chat/app/user/service/internal/data"
	"chat/app/user/service/internal/server"
	"chat/app/user/service/internal/service"
	"chat/pkg/registry"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"go.uber.org/zap"
)

// Injectors from wire.go:

// initApp init kratos application.
func initApp(confServer *conf.Server, confRegistry *conf.Registry, confData *conf.Data, logger log.Logger, zapLogger *zap.Logger) (*kratos.App, func(), error) {
	client := data.NewEntClient(confData, logger)
	discovery := data.NewDiscovery(confRegistry)
	clientConn := data.NewGroupClient(discovery)
	dataData, cleanup, err := data.NewData(client, clientConn, confData, logger)
	if err != nil {
		return nil, nil, err
	}
	userRepo := data.NewUserRepo(dataData, zapLogger)
	userRepository := biz.NewUserRepository(userRepo, zapLogger)
	userService := service.NewUserService(userRepository, zapLogger)
	grpcServer := server.NewGRPCServer(confServer, userService, logger)
	httpServer := server.NewHTTPServer(confServer, userService, logger)
	registrar := registry.NewConsulRegistry(zapLogger)
	app := newApp(logger, grpcServer, httpServer, registrar)
	return app, func() {
		cleanup()
	}, nil
}
