project:
  name: group_service
  version: latest
  mode: dev

server:
  http:
    addr: 0.0.0.0:8001
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9001
    timeout: 1s

data:
  database:
    driver: mysql
    source: root:123123@tcp(127.0.0.1:3306)/mychat
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s

log:
  log_path: "logs/"
  max_size: 1
  max_backups: 5
  max_age: 1
  compress: false