client_config:
  namespace_id: "802b2bf8-bc46-429c-999b-025868523e89"
  timeout_ms: 5000
  not_load_cache_at_start: true
  update_cache_when_empty: true
  log_dir: "logs/nacos/log"
  cache_dir: "logs/nacos/cache"
  rotate_time: "1h"
  max_age: 3
  log_level: "error"
  username: "nacos"
  password: "nacos"
server_configs:
  - ip_addr: "127.0.0.1"
    context_path: "/nacos"
    port: 8848
    scheme: "http"
node_config:
  data_id: "user-service"
  group: "dev"
