// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// protoc-gen-go-http v2.1.2

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

type GroupHTTPServer interface {
	GetGroupInfo(context.Context, *GetGroupInfoRequest) (*GetGroupInfoResponse, error)
}

func RegisterGroupHTTPServer(s *http.Server, srv GroupHTTPServer) {
	r := s.Route("/")
	r.POST("/v1/groupInfo", _Group_GetGroupInfo0_HTTP_Handler(srv))
}

func _Group_GetGroupInfo0_HTTP_Handler(srv GroupHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetGroupInfoRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, "/api.group.service.v1.Group/GetGroupInfo")
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetGroupInfo(ctx, req.(*GetGroupInfoRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetGroupInfoResponse)
		return ctx.Result(200, reply)
	}
}

type GroupHTTPClient interface {
	GetGroupInfo(ctx context.Context, req *GetGroupInfoRequest, opts ...http.CallOption) (rsp *GetGroupInfoResponse, err error)
}

type GroupHTTPClientImpl struct {
	cc *http.Client
}

func NewGroupHTTPClient(client *http.Client) GroupHTTPClient {
	return &GroupHTTPClientImpl{client}
}

func (c *GroupHTTPClientImpl) GetGroupInfo(ctx context.Context, in *GetGroupInfoRequest, opts ...http.CallOption) (*GetGroupInfoResponse, error) {
	var out GetGroupInfoResponse
	pattern := "/v1/groupInfo"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation("/api.group.service.v1.Group/GetGroupInfo"))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
