// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.18.0--rc1
// source: zap_log.proto

package conf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Log struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ZapLog *Log_ZapLog `protobuf:"bytes,1,opt,name=zap_log,json=zapLog,proto3" json:"zap_log,omitempty"`
}

func (x *Log) Reset() {
	*x = Log{}
	if protoimpl.UnsafeEnabled {
		mi := &file_zap_log_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Log) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Log) ProtoMessage() {}

func (x *Log) ProtoReflect() protoreflect.Message {
	mi := &file_zap_log_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Log.ProtoReflect.Descriptor instead.
func (*Log) Descriptor() ([]byte, []int) {
	return file_zap_log_proto_rawDescGZIP(), []int{0}
}

func (x *Log) GetZapLog() *Log_ZapLog {
	if x != nil {
		return x.ZapLog
	}
	return nil
}

type Log_ZapLog struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LogPath    string `protobuf:"bytes,1,opt,name=log_path,json=logPath,proto3" json:"log_path,omitempty"`
	MaxSize    int32  `protobuf:"varint,2,opt,name=max_size,json=maxSize,proto3" json:"max_size,omitempty"`
	MaxBackups int32  `protobuf:"varint,3,opt,name=max_backups,json=maxBackups,proto3" json:"max_backups,omitempty"`
	MaxAge     int32  `protobuf:"varint,4,opt,name=max_age,json=maxAge,proto3" json:"max_age,omitempty"`
	Compress   bool   `protobuf:"varint,5,opt,name=compress,proto3" json:"compress,omitempty"`
}

func (x *Log_ZapLog) Reset() {
	*x = Log_ZapLog{}
	if protoimpl.UnsafeEnabled {
		mi := &file_zap_log_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Log_ZapLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Log_ZapLog) ProtoMessage() {}

func (x *Log_ZapLog) ProtoReflect() protoreflect.Message {
	mi := &file_zap_log_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Log_ZapLog.ProtoReflect.Descriptor instead.
func (*Log_ZapLog) Descriptor() ([]byte, []int) {
	return file_zap_log_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Log_ZapLog) GetLogPath() string {
	if x != nil {
		return x.LogPath
	}
	return ""
}

func (x *Log_ZapLog) GetMaxSize() int32 {
	if x != nil {
		return x.MaxSize
	}
	return 0
}

func (x *Log_ZapLog) GetMaxBackups() int32 {
	if x != nil {
		return x.MaxBackups
	}
	return 0
}

func (x *Log_ZapLog) GetMaxAge() int32 {
	if x != nil {
		return x.MaxAge
	}
	return 0
}

func (x *Log_ZapLog) GetCompress() bool {
	if x != nil {
		return x.Compress
	}
	return false
}

var File_zap_log_proto protoreflect.FileDescriptor

var file_zap_log_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x7a, 0x61, 0x70, 0x5f, 0x6c, 0x6f, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x70, 0x6b, 0x67, 0x2e, 0x6c, 0x6f, 0x67, 0x22, 0xca, 0x01, 0x0a, 0x03, 0x4c, 0x6f, 0x67,
	0x12, 0x2c, 0x0a, 0x07, 0x7a, 0x61, 0x70, 0x5f, 0x6c, 0x6f, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x13, 0x2e, 0x70, 0x6b, 0x67, 0x2e, 0x6c, 0x6f, 0x67, 0x2e, 0x4c, 0x6f, 0x67, 0x2e,
	0x5a, 0x61, 0x70, 0x4c, 0x6f, 0x67, 0x52, 0x06, 0x7a, 0x61, 0x70, 0x4c, 0x6f, 0x67, 0x1a, 0x94,
	0x01, 0x0a, 0x06, 0x5a, 0x61, 0x70, 0x4c, 0x6f, 0x67, 0x12, 0x19, 0x0a, 0x08, 0x6c, 0x6f, 0x67,
	0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6c, 0x6f, 0x67,
	0x50, 0x61, 0x74, 0x68, 0x12, 0x19, 0x0a, 0x08, 0x6d, 0x61, 0x78, 0x5f, 0x73, 0x69, 0x7a, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x6d, 0x61, 0x78, 0x53, 0x69, 0x7a, 0x65, 0x12,
	0x1f, 0x0a, 0x0b, 0x6d, 0x61, 0x78, 0x5f, 0x62, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x73, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x6d, 0x61, 0x78, 0x42, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x73,
	0x12, 0x17, 0x0a, 0x07, 0x6d, 0x61, 0x78, 0x5f, 0x61, 0x67, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x06, 0x6d, 0x61, 0x78, 0x41, 0x67, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x6f, 0x6d,
	0x70, 0x72, 0x65, 0x73, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x63, 0x6f, 0x6d,
	0x70, 0x72, 0x65, 0x73, 0x73, 0x42, 0x12, 0x5a, 0x10, 0x63, 0x68, 0x61, 0x74, 0x2f, 0x70, 0x6b,
	0x67, 0x2f, 0x6c, 0x6f, 0x67, 0x3b, 0x6c, 0x6f, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_zap_log_proto_rawDescOnce sync.Once
	file_zap_log_proto_rawDescData = file_zap_log_proto_rawDesc
)

func file_zap_log_proto_rawDescGZIP() []byte {
	file_zap_log_proto_rawDescOnce.Do(func() {
		file_zap_log_proto_rawDescData = protoimpl.X.CompressGZIP(file_zap_log_proto_rawDescData)
	})
	return file_zap_log_proto_rawDescData
}

var file_zap_log_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_zap_log_proto_goTypes = []interface{}{
	(*Log)(nil),        // 0: pkg.log.Log
	(*Log_ZapLog)(nil), // 1: pkg.log.Log.ZapLog
}
var file_zap_log_proto_depIdxs = []int32{
	1, // 0: pkg.log.Log.zap_log:type_name -> pkg.log.Log.ZapLog
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_zap_log_proto_init() }
func file_zap_log_proto_init() {
	if File_zap_log_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_zap_log_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Log); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_zap_log_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Log_ZapLog); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_zap_log_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_zap_log_proto_goTypes,
		DependencyIndexes: file_zap_log_proto_depIdxs,
		MessageInfos:      file_zap_log_proto_msgTypes,
	}.Build()
	File_zap_log_proto = out.File
	file_zap_log_proto_rawDesc = nil
	file_zap_log_proto_goTypes = nil
	file_zap_log_proto_depIdxs = nil
}
