// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"chat/app/group/service/internal/biz"
	"chat/app/group/service/internal/conf"
	"chat/app/group/service/internal/data"
	"chat/app/group/service/internal/server"
	"chat/app/group/service/internal/service"
	"chat/pkg/registry"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"go.uber.org/zap"
)

// Injectors from wire.go:

// initApp init kratos application.
func initApp(confServer *conf.Server, confData *conf.Data, logger log.Logger, zapLogger *zap.Logger) (*kratos.App, func(), error) {
	client := data.NewEntClient(confData, zapLogger)
	dataData, cleanup, err := data.NewData(client, confData, logger)
	if err != nil {
		return nil, nil, err
	}
	groupRepo := data.NewGroupRepo(dataData, zapLogger)
	groupRepository := biz.NewGroupRepository(groupRepo, zapLogger)
	groupService := service.NewUserService(groupRepository, zapLogger)
	grpcServer := server.NewGRPCServer(confServer, groupService, logger)
	httpServer := server.NewHTTPServer(confServer, groupService, logger)
	registrar := registry.NewConsulRegistry(zapLogger)
	app := newApp(logger, grpcServer, httpServer, registrar)
	return app, func() {
		cleanup()
	}, nil
}
